### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by Ardor-Wu** [Peachypie98/RivaGAN#4]
Thank you for sharing the code! Do you have trained checkpoints or is there a way to use their official checkpoint, which ends with .onnx? Thanks!

**Comment by Peachypie98** [comment]
At the moment, I have only got a .pt file for pretrained model. (Trained in 32-bits)

**Comment by Ardor-Wu** [comment]
Could you share that checkpoint? I tried to train with the default setting yet the model does not seem to converge well, with ACC 0.5.
<img width="1797" alt="Screenshot 2024-04-17 at 10 13 16 AM" src="https://github.com/Peachypie98/RivaGAN/assets/70617529/d9025698-93e3-4d44-bb06-6943409b34c1">

**Comment by Peachypie98** [comment]
I have updated the repository, which now includes the pre-trained model weight.
