### ISSUE TITLE
output file has no audio

### ISSUE THREAD

**Issue by jeffRao** [Peachypie98/RivaGAN#6]
i followed the step to convert video. but i found the output video has no audio. 

my command is:

> python inference.py --model_weight /data/RivaGAN/RivaGAN/model_weight/rivagan_32bit_model.pt --random_data No --your_data "1100 1001 0011 0000 1111 0101 1100 0011" --fps 30 --video_location /data/RivaGAN/data/test_video.mp4 --data_dim 32

output logs :
```logs
**** Inference Configurations ****
1. Model: RivaGAN
2. Device: cuda
3. Data Dimension: 32
4. Model Weight: /data/RivaGAN/RivaGAN/model_weight/rivagan_32bit_model.pt
5. Video Location: /data/RivaGAN/data/test_video.mp4
6. Output FPS: 30

Model's weight is loaded!
Data: (1, 1, 0, 0) (1, 0, 0, 1) (0, 0, 1, 1) (0, 0, 0, 0) (1, 1, 1, 1) (0, 1, 0, 1) (1, 1, 0, 0) (0, 0, 1, 1)
Encoding Watermark to Video...
Video Total Frame: 7998
Video Width: 960
Video Height: 544
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7998/7998 [03:18<00:00, 40.39it/s]
Extracing Data Watermark...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7998/7998 [03:12<00:00, 41.47it/s]
Inference Time (Complete): 390.94s
Inference Time on Full Frame (Encoder Only): 198.075s
Inference Time on Each Frame (Encoder Only): 0.025s
Inference Time on Full Frame (Decoder Only): 192.860s
Inference Time on Each Frame (Decoder Only): 0.024s
Average Accuracy Data: 0.98
```

Do I need to add audio after the video conversion is complete? Or can we achieve the effect of outputting video with audio by adjusting parameters?

**Comment by Peachypie98** [comment]
The model doesn't output video with audio. Therefore, you have to add the audio manually after the video conversion is complete.

**Comment by jeffRao** [comment]
> The model doesn't output video with audio. Therefore, you have to add the audio manually after the video conversion is complete.

OKay，Thx
